"""Write isolated OpenMW / TES3MP configs for multiplayer packs."""

from __future__ import annotations

import json
import os
import shutil
import sys
import ctypes
from pathlib import Path

from .detect import MorrowindInstall
from .packs import (
    VANILLA,
    PackDef,
    active_archives,
    active_content,
    get_pack,
    write_required_data_files,
)
from .paths import (
    DEFAULT_PORT,
    TES3MP_VERSION,
    config_dir,
    server_state_dir,
)


def _cfg_escape(path: Path) -> str:
    return str(path).replace("\\", "/")


def openmw_user_config_dir() -> Path:
    """Match OpenMW 0.47's Windows Documents/My Games/OpenMW location."""
    if os.name == "nt":
        documents = ctypes.create_unicode_buffer(32768)
        # CSIDL_PERSONAL is the same known folder used by TES3MP/OpenMW 0.47.
        result = ctypes.windll.shell32.SHGetFolderPathW(None, 5, None, 0, documents)
        if result == 0 and documents.value:
            return Path(documents.value) / "My Games" / "OpenMW"
    return Path.home() / "Documents" / "My Games" / "OpenMW"


def ensure_native_openmw_profile(
    install: MorrowindInstall,
    pack: PackDef | None = None,
    *,
    directory: Path | None = None,
) -> Path:
    """Prepare the native profile TES3MP 0.8.1 actually reads, without a wizard.

    Existing compatible profiles are preserved byte-for-byte. Missing profiles
    receive only the detected game path, archives, and selected content. A
    profile with a different plugin list is rejected instead of being silently
    overwritten.
    """
    pack = pack or VANILLA
    directory = directory or openmw_user_config_dir()
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / "openmw.cfg"
    original = path.read_text(encoding="utf-8") if path.is_file() else ""

    content_values: list[str] = []
    data_values: list[str] = []
    archive_values: list[str] = []
    for raw_line in original.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        value = value.strip().strip('"')
        if key.strip() == "content":
            content_values.append(value)
        elif key.strip() in ("data", "data-local"):
            data_values.append(value)
        elif key.strip() == "fallback-archive":
            archive_values.append(value)

    required_content = active_content(install, pack)
    if content_values and [item.casefold() for item in content_values] != [
        item.casefold() for item in required_content
    ]:
        raise RuntimeError(
            "Your OpenMW profile loads a different plugin list. Open openmw-wizard.exe "
            "in the TES3MP folder, select this Morrowind install, and try again."
        )

    additions: list[str] = []
    normalized_data = {
        value.replace("\\", "/").rstrip("/").casefold() for value in data_values
    }
    game_data = _cfg_escape(install.data_files)
    if game_data.rstrip("/").casefold() not in normalized_data:
        additions.append(f'data="{game_data}"')

    archive_keys = {value.casefold() for value in archive_values}
    for archive in active_archives(install, pack):
        if archive.casefold() not in archive_keys:
            additions.append(f"fallback-archive={archive}")

    if not content_values:
        additions.extend(f"content={plugin}" for plugin in required_content)

    if additions:
        managed = "\n".join(
            [
                "# MorrowFriends: automatically prepared for TES3MP 0.8.1",
                *additions,
            ]
        )
        updated = original.rstrip() + ("\n\n" if original.strip() else "") + managed + "\n"
        staging = path.with_name(path.name + ".tmp")
        staging.write_text(updated, encoding="utf-8")
        staging.replace(path)
    return path


def write_openmw_cfg(install: MorrowindInstall, pack: PackDef | None = None) -> Path:
    pack = pack or VANILLA
    cfg_path = config_dir() / "openmw.cfg"
    data = _cfg_escape(install.data_files)
    lines = [
        "# Generated by MorrowFriends — do not mix with Documents\\My Games\\OpenMW",
        f"# pack={pack.id}",
        f'data="{data}"',
    ]
    for archive in active_archives(install, pack):
        lines.append(f"fallback-archive={archive}")
    for master in active_content(install, pack):
        lines.append(f"content={master}")
    lines.append("encoding=win1252")
    cfg_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return cfg_path


def write_settings_cfg() -> Path:
    path = config_dir() / "settings.cfg"
    if path.is_file():
        return path
    # Borderless windowed, NOT exclusive fullscreen. Exclusive fullscreen takes
    # the display in a way that suppresses every other window, so the always-on-
    # top nearby/voice strip cannot draw over the game and alt-tabbing costs a
    # video mode switch. TES3MP's Lua API has no HUD/per-frame/DrawText hook
    # (only modal MessageBox dialogs that steal input), so an overlay window is
    # the ONLY way to show voice state during play — and it needs this to work.
    # Borderless at native resolution looks identical to fullscreen.
    path.write_text(
        "[General]\n"
        "encoding = win1252\n"
        "\n"
        "[Video]\n"
        "fullscreen = false\n"
        "window border = false\n"
        "\n"
        "[Game]\n"
        "show owned = 1\n",
        encoding="utf-8",
    )
    return path


def ensure_overlay_friendly_video(path: Path | None = None) -> bool:
    """Switch an EXISTING settings.cfg off exclusive fullscreen.

    write_settings_cfg() refuses to touch a file that already exists, so every
    install created before this change is still stuck in exclusive fullscreen
    where no overlay can appear. Returns True when a change was made.
    """
    target = path or (config_dir() / "settings.cfg")
    if not target.is_file():
        return False
    try:
        original = target.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False

    lines = original.splitlines()
    section = ""
    out: list[str] = []
    saw_fullscreen = False
    saw_border = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            # Close out [Video] before leaving it, adding anything missing.
            if section == "video":
                if not saw_fullscreen:
                    out.append("fullscreen = false")
                    saw_fullscreen = True
                if not saw_border:
                    out.append("window border = false")
                    saw_border = True
            section = stripped[1:-1].strip().casefold()
            out.append(line)
            continue
        if section == "video":
            key = stripped.split("=", 1)[0].strip().casefold() if "=" in stripped else ""
            if key == "fullscreen":
                out.append("fullscreen = false")
                saw_fullscreen = True
                continue
            if key == "window border":
                out.append("window border = false")
                saw_border = True
                continue
        out.append(line)

    if section == "video":
        if not saw_fullscreen:
            out.append("fullscreen = false")
            saw_fullscreen = True
        if not saw_border:
            out.append("window border = false")
            saw_border = True

    if not saw_fullscreen:
        out.extend(["", "[Video]", "fullscreen = false", "window border = false"])

    updated = "\n".join(out) + "\n"
    if updated == original:
        return False
    staging = target.with_name(target.name + ".tmp")
    staging.write_text(updated, encoding="utf-8")
    staging.replace(target)
    return True


def read_client_destination(path: Path) -> tuple[str, int]:
    """Return (destinationAddress, port) actually on disk, or ("", 0)."""
    if not path.is_file():
        return "", 0
    host = ""
    port = 0
    try:
        for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
            line = raw.strip()
            if "=" not in line or line.startswith("#"):
                continue
            key, value = (part.strip() for part in line.split("=", 1))
            if key.casefold() == "destinationaddress":
                host = value
            elif key.casefold() == "port" and not port:
                try:
                    port = int(value)
                except ValueError:
                    port = 0
    except OSError:
        return "", 0
    return host, port


def verify_client_destination(tes3mp_root: Path, host: str, port: int) -> str:
    """Confirm the launched engine will really dial host:port.

    TES3MP takes its destination ONLY from tes3mp-client-default.cfg, and a
    wrong value fails silently — the game opens and connects to nobody. The
    stock file ships with `destinationAddress = 127.0.0.1`, so any path that
    launches without rewriting it sends the player to their own machine.
    That is how rettycombine spent an evening stuck (2026-08-18); he fixed it
    by hand-editing this exact field.

    Returns "" when correct, else a human-readable mismatch description.
    """
    actual_host, actual_port = read_client_destination(
        tes3mp_root / "tes3mp-client-default.cfg"
    )
    if not actual_host:
        return "the TES3MP client config has no destination address"
    if actual_host.casefold() != host.casefold():
        return f"TES3MP would connect to {actual_host}, not {host}"
    if actual_port and port and actual_port != port:
        return f"TES3MP would use port {actual_port}, not {port}"
    return ""


def write_client_cfg(host: str, port: int = DEFAULT_PORT, password: str = "") -> Path:
    path = config_dir() / "tes3mp-client-default.cfg"
    content = (
        "[General]\n"
        f"destinationAddress = {host}\n"
        f"port = {port}\n"
        f"password = {password}\n"
        "logLevel = 1\n"
        "\n"
        "[Master]\n"
        "address = master.tes3mp.com\n"
        "port = 25561\n"
        "\n"
        "[Chat]\n"
        "keySay = Y\n"
        "keyChatMode = F2\n"
        "x = 0\n"
        "y = 0\n"
        "w = 390\n"
        "h = 250\n"
        # Chat auto-hide delay. Feeds GUIChat::setDelay() via GUIController::
        # setupChat(), and GUIChat::update() hides the window this many seconds
        # after the last message in CHAT_HIDDENMODE. 2s keeps the push-to-talk
        # indicator from lingering on screen after the key is released; 5s felt
        # like a stuck message.
        "delay = 2.0\n"
    )
    path.write_text(content, encoding="utf-8")
    return path


def write_server_cfg(
    hostname: str = "MorrowFriends",
    port: int = DEFAULT_PORT,
    password: str = "",
    maximum_players: int = 16,
) -> Path:
    path = config_dir() / "tes3mp-server-default.cfg"
    content = (
        "[General]\n"
        "localAddress = 0.0.0.0\n"
        f"port = {port}\n"
        f"maximumPlayers = {maximum_players}\n"
        f"hostname = {hostname}\n"
        "logLevel = 1\n"
        f"password = {password}\n"
        "\n"
        "[Plugins]\n"
        "home = ./server\n"
        "plugins = serverCore.lua\n"
        "\n"
        "[MasterServer]\n"
        "enabled = false\n"
        "address = master.tes3mp.com\n"
        "port = 25561\n"
        "rate = 10000\n"
    )
    path.write_text(content, encoding="utf-8")
    return path


ROSTER_SCRIPT_NAME = "morrowfriends_roster.lua"
ROSTER_REQUIRE_LINE = 'require("custom/morrowfriends_roster")\n'
PLAYER_TP_SCRIPT_NAME = "morrowfriends_player_teleport.lua"
PLAYER_TP_REQUIRE_LINE = 'require("custom/morrowfriends_player_teleport")\n'
FRIENDLY_FIRE_SCRIPT_NAME = "morrowfriends_friendly_fire.lua"
FRIENDLY_FIRE_REQUIRE_LINE = 'require("custom/morrowfriends_friendly_fire")\n'


def install_roster_script(tes3mp_root: Path) -> None:
    """Install MorrowFriends server hooks and wire them in idempotently."""
    custom_dir = tes3mp_root / "server" / "scripts" / "custom"
    custom_dir.mkdir(parents=True, exist_ok=True)

    installed_modules: list[tuple[str, str]] = []
    for script_name, module_name, require_line in (
        (ROSTER_SCRIPT_NAME, "custom/morrowfriends_roster", ROSTER_REQUIRE_LINE),
        (
            PLAYER_TP_SCRIPT_NAME,
            "custom/morrowfriends_player_teleport",
            PLAYER_TP_REQUIRE_LINE,
        ),
        (
            FRIENDLY_FIRE_SCRIPT_NAME,
            "custom/morrowfriends_friendly_fire",
            FRIENDLY_FIRE_REQUIRE_LINE,
        ),
    ):
        candidates = [
            Path(__file__).resolve().parents[1]
            / "packaging"
            / "tes3mp_custom_scripts"
            / script_name,
            Path(getattr(sys, "_MEIPASS", "")) / script_name,
        ]
        src = next((candidate for candidate in candidates if candidate.is_file()), None)
        if src is not None:
            shutil.copy2(src, custom_dir / script_name)
            installed_modules.append((module_name, require_line))

    loader = tes3mp_root / "server" / "scripts" / "customScripts.lua"
    if not loader.is_file():
        return
    text = loader.read_text(encoding="utf-8")
    changed = False
    for module_name, require_line in installed_modules:
        if module_name not in text:
            text = text.rstrip() + "\n" + require_line
            changed = True
    if changed:
        loader.write_text(text, encoding="utf-8")


def read_live_roster(tes3mp_root: Path) -> list[dict]:
    """Read the roster JSON written by morrowfriends_roster.lua. Empty list if server isn't up yet."""
    path = tes3mp_root / "server" / "data" / "live_players.json"
    if not path.is_file():
        return []
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(data, list):
            return data
        if isinstance(data, dict) and isinstance(data.get("players"), list):
            return data["players"]
        return []
    except (OSError, json.JSONDecodeError):
        return []


def read_live_position_snapshot(tes3mp_root: Path) -> dict:
    """Read the versioned TES3MP position feed used by proximity voice."""
    path = tes3mp_root / "server" / "data" / "live_players.json"
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(data, dict) and isinstance(data.get("players"), list):
            data["_fileMtime"] = path.stat().st_mtime
            return data
        # Compatibility with the original roster-only bridge.
        if isinstance(data, list):
            return {
                "version": 0,
                "sequence": 0,
                "players": data,
                "_fileMtime": path.stat().st_mtime,
            }
        return {}
    except (OSError, json.JSONDecodeError):
        return {}


def read_voice_claims(tes3mp_root: Path) -> dict:
    """Read short-lived in-game voice claims for the outbound relay."""
    path = tes3mp_root / "server" / "data" / "voice_claims.json"
    if not path.is_file():
        return {"version": 1, "claims": {}}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(data, dict) and isinstance(data.get("claims"), dict):
            return data
        return {"_readError": True}
    except (OSError, json.JSONDecodeError):
        # Claims are sacred control state. Keep the last acknowledged set when
        # a writer is briefly between bytes instead of publishing a false clear.
        return {"_readError": True}


def write_ptt_state(tes3mp_root: Path, player_name: str, talking: bool) -> None:
    """Publish the host's push-to-talk state for the in-game indicator.

    Deliberately NOT sent through host_commands.json: that channel polls once a
    second and holds a single command, so rapid PTT presses would be dropped and
    the indicator would lag by up to a second. The roster Lua already runs a
    200ms timer, so it reads this file on the same tick it writes positions.

    Only the HOST's own microphone is represented. The relay tracks position and
    mixing but not who is speaking, so there is no source for other players'
    talking state (verified 2026-08-18).
    """
    path = tes3mp_root / "server" / "data" / "ptt_state.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "version": 1,
        "player": player_name.strip(),
        "talking": bool(talking),
    }
    staging = path.with_name(path.name + ".tmp")
    staging.write_text(json.dumps(payload), encoding="utf-8")
    staging.replace(path)


def write_host_command(tes3mp_root: Path, command: dict) -> None:
    """Write one action for morrowfriends_roster.lua's poll timer to pick up (~1s latency)."""
    path = tes3mp_root / "server" / "data" / "host_commands.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    staging = path.with_name(path.name + ".tmp")
    staging.write_text(json.dumps(command), encoding="utf-8")
    staging.replace(path)


def read_host_command_result(tes3mp_root: Path) -> dict:
    """Read the latest acknowledgement written by the host-command Lua bridge."""
    path = tes3mp_root / "server" / "data" / "host_command_result.json"
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else {}
    except (OSError, json.JSONDecodeError):
        return {}


def sync_engine_configs(
    tes3mp_root: Path,
    install: MorrowindInstall | None = None,
    pack: PackDef | None = None,
    is_server: bool = False,
) -> None:
    """Copy client/server cfg and requiredDataFiles into the TES3MP install."""
    cfg = config_dir()
    for name in ("tes3mp-client-default.cfg", "tes3mp-server-default.cfg"):
        src = cfg / name
        if src.is_file():
            shutil.copy2(src, tes3mp_root / name)

    server_data = tes3mp_root / "server" / "data"
    server_data.mkdir(parents=True, exist_ok=True)

    if install is not None:
        pack = pack or VANILLA
        write_required_data_files(
            install,
            pack,
            server_data / "requiredDataFiles.json",
        )

    if is_server:
        install_roster_script(tes3mp_root)

    server_state_dir()


def ensure_mp_profile(install: MorrowindInstall, pack: PackDef | None = None) -> Path:
    pack = pack or VANILLA
    write_openmw_cfg(install, pack)
    write_settings_cfg()
    # Existing installs were written with exclusive fullscreen, which hides the
    # voice/nearby overlay completely. write_settings_cfg() will not touch a
    # file that already exists, so migrate it here.
    ensure_overlay_friendly_video()
    return config_dir()


def profile_banner(pack_id: str = "vanilla") -> str:
    pack = get_pack(pack_id)
    return f"{pack.label} · TES3MP {TES3MP_VERSION} · shared story"
