#!/usr/bin/env bash
# Dedicated TES3MP 0.8.1 server for a Hetzner (or any Linux) box.
# Runs the same engine version and coop rules as MorrowFriends' local Host mode,
# so invites generated by either side are compatible.
#
# Usage:
#   sudo ./hetzner_setup.sh install        # download + unpack server
#   ./hetzner_setup.sh copy-data <path>    # copy Morrowind.esm/Tribunal.esm/Bloodmoon.esm + .bsa from a local Data Files dir (scp them here first)
#   ./hetzner_setup.sh configure           # apply shared-story rules + write server cfg
#   ./hetzner_setup.sh start               # run in foreground (use systemd/tmux for real use)
set -euo pipefail

TES3MP_VERSION="0.8.1"
INSTALL_DIR="/opt/tes3mp"
DOWNLOAD_URL="https://github.com/TES3MP/TES3MP/releases/download/tes3mp-0.8.1/tes3mp-GNU%2BLinux-x86_64-release-0.8.1-68954091c5-6da3fdea59.tar.gz"
TARBALL="/tmp/tes3mp-linux.tar.gz"
PORT="${TES3MP_PORT:-25565}"
HOSTNAME_LABEL="${TES3MP_HOSTNAME:-MorrowFriends}"
PASSWORD="${TES3MP_PASSWORD:-}"

# GOTY masters/archives required in server/data before guests can join.
GOTY_MASTERS=(Morrowind.esm Tribunal.esm Bloodmoon.esm)
GOTY_ARCHIVES=(Morrowind.bsa Tribunal.bsa Bloodmoon.bsa)

# Same shared-story defaults as app/coop.py — keep these two in sync by hand.
declare -A COOP_RULES=(
  [shareJournal]=true
  [shareFactionRanks]=true
  [shareFactionExpulsion]=false
  [shareFactionReputation]=true
  [shareTopics]=true
  [shareBounty]=false
  [shareReputation]=true
  [shareMapExploration]=false
  [shareVideos]=true
)

cmd_install() {
  mkdir -p "$INSTALL_DIR"
  echo "Downloading TES3MP ${TES3MP_VERSION} Linux server (~58 MiB)..."
  curl -fL "$DOWNLOAD_URL" -o "$TARBALL"
  tar -xzf "$TARBALL" -C "$INSTALL_DIR" --strip-components=1
  rm -f "$TARBALL"
  echo "Installed to $INSTALL_DIR"
  ls "$INSTALL_DIR"/tes3mp-server* || { echo "tes3mp-server binary not found after extract" >&2; exit 1; }
}

cmd_copy_data() {
  local src="${1:?Usage: copy-data <path-to-local-Data-Files-dir-already-on-this-box>}"
  local dest="$INSTALL_DIR/server/data"
  mkdir -p "$dest"
  for f in "${GOTY_MASTERS[@]}" "${GOTY_ARCHIVES[@]}"; do
    if [[ ! -f "$src/$f" ]]; then
      echo "Missing required file: $src/$f" >&2
      exit 1
    fi
    cp -v "$src/$f" "$dest/"
  done
  echo "Data files staged in $dest"
}

cmd_configure() {
  local cfg="$INSTALL_DIR/tes3mp-server-default.cfg"
  cat > "$cfg" <<EOF
[General]
localAddress = 0.0.0.0
port = ${PORT}
maximumPlayers = 16
hostname = ${HOSTNAME_LABEL}
logLevel = 1
password = ${PASSWORD}

[Plugins]
home = ./server
plugins = serverCore.lua

[MasterServer]
enabled = false
address = master.tes3mp.com
port = 25561
rate = 10000
EOF
  echo "Wrote $cfg"

  local lua="$INSTALL_DIR/server/scripts/config.lua"
  if [[ ! -f "$lua" ]]; then
    echo "Missing $lua — run 'install' first" >&2
    exit 1
  fi
  for key in "${!COOP_RULES[@]}"; do
    val="${COOP_RULES[$key]}"
    if grep -qE "config\.${key}\s*=\s*(true|false)" "$lua"; then
      sed -i -E "s/config\.${key}\s*=\s*(true|false)/config.${key} = ${val}/" "$lua"
    else
      echo "config.${key} = ${val}" >> "$lua"
    fi
  done
  echo "Applied shared-story coop rules to $lua"
}

cmd_start() {
  cd "$INSTALL_DIR"
  echo "Starting tes3mp-server on port ${PORT} (Ctrl+C to stop)..."
  ./tes3mp-server --config "$INSTALL_DIR" --resources "$INSTALL_DIR/resources"
}

case "${1:-}" in
  install) cmd_install ;;
  copy-data) shift; cmd_copy_data "$@" ;;
  configure) cmd_configure ;;
  start) cmd_start ;;
  *)
    echo "Usage: $0 {install|copy-data <path>|configure|start}" >&2
    exit 1
    ;;
esac
